/**
  ******************************************************************************
  * @file    alarm_file.c
  * @author  Auto-generated by LINGMA
  * @brief   闹钟数据文件操作模块
  ******************************************************************************
  */

#include "alarm_file.h"
#include "alarm_all.h"
#include "../ff16/ff.h"
#include <string.h>
#include <stdio.h>
#include <stdint.h>

#ifdef STM32F4XX
#include "stm32f4xx.h"
#endif

// 闹钟数据文件路径
#define ALARM_DATA_FILE "0:alarms.dat"

// 定义基本类型
typedef unsigned int    UINT;
typedef uint16_t        WORD;
typedef uint32_t        DWORD;

// 定义NULL宏
#ifndef NULL
#define NULL ((void *)0)
#endif

// 声明全局变量
extern Alarm_TypeDef g_alarms[MAX_ALARMS];
extern uint8_t g_alarm_count;

/**
 * @brief 保存闹钟到文件
 */
void Alarms_Save(void)
{
    FIL file;
    FRESULT fr;
    UINT bw;
    
    // 打开文件用于写入（如果不存在则创建，存在则覆盖）
    fr = f_open(&file, ALARM_DATA_FILE, FA_CREATE_ALWAYS | FA_WRITE);
    if (fr != FR_OK) {
        return;
    }
    
    // 写入闹钟数量
    fr = f_write(&file, &g_alarm_count, sizeof(g_alarm_count), &bw);
    if (fr != FR_OK || bw != sizeof(g_alarm_count)) {
        f_close(&file);
        return;
    }
    
    // 如果有闹钟，写入闹钟数据
    if (g_alarm_count > 0) {
        WORD alarm_data_size = g_alarm_count * sizeof(Alarm_TypeDef);
        fr = f_write(&file, g_alarms, alarm_data_size, &bw);
        if (fr != FR_OK || bw != alarm_data_size) {
            f_close(&file);
            return;
        }
    }
    
    // 关闭文件
    f_close(&file);
}

/**
 * @brief 从文件加载闹钟
 */
void Alarms_Load(void)
{
    FIL file;
    FRESULT fr;
    UINT br;
    
    // 打开文件用于读取
    fr = f_open(&file, ALARM_DATA_FILE, FA_READ);
    if (fr != FR_OK) {
        // 文件不存在或其他错误，初始化为空的闹钟列表
        g_alarm_count = 0;
        return;
    }
    
    // 读取闹钟数量
    fr = f_read(&file, &g_alarm_count, sizeof(g_alarm_count), &br);
    if (fr != FR_OK || br != sizeof(g_alarm_count)) {
        f_close(&file);
        g_alarm_count = 0;
        return;
    }
    
    // 检查数据有效性
    if (g_alarm_count > MAX_ALARMS) {
        g_alarm_count = 0;
        f_close(&file);
        return;
    }
    
    // 如果有闹钟，读取闹钟数据
    if (g_alarm_count > 0) {
        WORD alarm_data_size = g_alarm_count * sizeof(Alarm_TypeDef);
        fr = f_read(&file, g_alarms, alarm_data_size, &br);
        if (fr != FR_OK || br != alarm_data_size) {
            g_alarm_count = 0;
            f_close(&file);
            return;
        }
        
        // 验证读取的数据是否合理（简单的边界检查）
        for (uint8_t i = 0; i < g_alarm_count; i++) {
            if (g_alarms[i].hour > 23 || g_alarms[i].minute > 59 || g_alarms[i].second > 59) {
                g_alarm_count = 0;
                f_close(&file);
                return;
            }
        }
    }
    
    // 关闭文件
    f_close(&file);
}
